USE condenser_db;

CREATE TABLE IF NOT EXISTS material_cost_preset (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL COMMENT '所属用户ID',
  type VARCHAR(20) NOT NULL COMMENT '类型: COLLECTOR/FIN/TUBE/FOLD_TUBE',
  spec VARCHAR(100) NOT NULL COMMENT '规格型号',
  factor DECIMAL(10,6) DEFAULT NULL COMMENT '计量系数',
  weight DECIMAL(10,6) DEFAULT NULL COMMENT '重量(KG) 集流管/扁管/折叠扁管用',
  thickness DECIMAL(10,6) DEFAULT NULL COMMENT '料厚 翅片用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_type (user_id, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='材料预算系数预存';
